---
title: "DREAN RV Fig1cd"
author: "Slim FOURATI"
date: "12/09/2014"
output: github_document
---

```{r load-packages}
suppressPackageStartupMessages(library(package = "knitr"))
suppressPackageStartupMessages(library(package = "Biobase"))
suppressPackageStartupMessages(library(package = "ggplot2"))
suppressPackageStartupMessages(library(package = "dplyr"))
suppressPackageStartupMessages(library(package = "tidyr"))
```

set session options
```{r session-options}
knitr::opts_chunk$set(echo = TRUE) # do not echo chunks
opts_chunk$set(tidy = FALSE, fig.path = "../figure/")
options(dplyr.summarise.inform = FALSE)
workDir <- dirname(getwd())
```

```{r load-eset}
load(file = file.path(workDir, "output/dream.eset.RData"))
``` 

```{r plot-fig1a}
pData(eset) %>%
  mutate(SET = gsub(pattern = ".+[c|C]hallenge_([^_]+).+",
                    replacement = "\\1",
                    Filename),
         VIRUS = gsub(pattern     = " Duke| UVA|DEE[^ ]+ ", 
                      replacement = "",
                      STUDYID),
         VIRUS = ifelse(test = !is.na(SHAM),
                        yes  = "SHAM",
                        no   = VIRUS)) %>%
  select(SUBJECTID, VIRUS, SET) %>%
  distinct() %>%
  group_by(SET) %>%
  summarize(n = n())
``` 

```{r plot-fig1c}
plotDF <- pData(eset) %>%
  mutate(SET = gsub(pattern = ".+[c|C]hallenge_([^_]+).+",
                    replacement = "\\1",
                    Filename),
         VIRUS = gsub(pattern     = " Duke| UVA|DEE[^ ]+ ", 
                      replacement = "",
                      STUDYID),
         VIRUS = ifelse(test = !is.na(SHAM),
                        yes  = "SHAM",
                        no   = VIRUS)) %>% 
  select(SUBJECTID, SET, VIRUS, TIMEHOURS) %>%
  distinct() %>%
  group_by(SET, VIRUS, TIMEHOURS) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(VIRUS = factor(VIRUS, levels = rev(sort(unique(VIRUS)))),
         SET   = factor(SET, levels = rev(sort(unique(SET)))))

ggplot(data    = plotDF,
       mapping = aes(x = TIMEHOURS, y = VIRUS)) +
  geom_text(mapping = aes(label = n)) +
  scale_x_continuous(limits = c(-30, 24)) +
  geom_vline(xintercept = unique(plotDF$TIMEHOURS), linetype = 3) +
  facet_wrap(facets = ~SET, ncol = 1, scale = "free") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
``` 

```{r plot-fig1d-sc1-sc2}
plotDF <- pData(eset) %>%
  mutate(SET = gsub(pattern = ".+[c|C]hallenge_([^_]+).+",
                    replacement = "\\1",
                    Filename),
         VIRUS = gsub(pattern     = " Duke| UVA|DEE[^ ]+ ", 
                      replacement = "",
                      STUDYID)) %>%
  filter(is.na(SHAM) & SET %in% "training") %>%
  select(SUBJECTID, SHEDDING_SC1, SYMPTOMATIC_SC2, VIRUS) %>%
  distinct() %>%
  gather(cname, value, -SUBJECTID, -VIRUS) %>%
  group_by(cname, value, VIRUS) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(value = factor(value))

ggplot(data = plotDF,
       mapping = aes(x = VIRUS, y = n, fill = value)) +
  geom_bar(stat = "identity", width = 0.8) +
  coord_flip() +
  facet_wrap(facets = ~cname, ncol = 1,
             scale = "free") +
  scale_y_continuous(expand = c(0, 0)) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank())

percentDF <- plotDF %>%
  group_by(cname,  VIRUS) %>%
  summarize(total = sum(n)) %>%
  merge(x = plotDF, by = c("cname", "VIRUS")) %>%
  mutate(percent = n/total * 100,
         percent = round(percent))
``` 

```{r plot-fig1c-sc3}
plotDF <- pData(eset) %>%
  mutate(SET = gsub(pattern = ".+[c|C]hallenge_([^_]+).+",
                    replacement = "\\1",
                    Filename),
         VIRUS = gsub(pattern     = " Duke| UVA|DEE[^ ]+ ", 
                      replacement = "",
                      STUDYID)) %>%
  filter(is.na(SHAM) & SET %in% "training") %>%
  select(SUBJECTID, LOGSYMPTSCORE_SC3, VIRUS) %>%
  distinct()

ggplot(data = plotDF,
       mapping = aes(x = VIRUS, y = LOGSYMPTSCORE_SC3)) +
  geom_boxplot(fill = "transparent", width = 0.8, outlier.colour = "transparent") +
  geom_dotplot(binaxis = "y", binwidth = 0.001, stackdir = "center", dotsize = 20) +
  coord_flip() +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank())
``` 

```{r session-info}
sessionInfo()
```
